# Generated by Django 4.2.4 on 2023-08-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogcontent', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_review', models.DateField(auto_now_add=True)),
                ('review', models.TextField(max_length=300)),
                ('post_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcontent.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
