# Generated by Django 4.2.4 on 2023-09-11 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogcontent", "0004_remove_blog_liked_like"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ("-date_of_post",)},
        ),
    ]
